from enum import Enum

FPS: int = 40

TILE_SIZE: int = 8
TILE_BG_NUM: int = 96  # 96以下のタイル番号は背景とみなし、当たり判定を行わない

PLYAER_STEP = 1
JUMP = -4
GRAVITY = 1
GRAVITY_MAX = 3
GRAVITY_INTERVAL = 3

P_IMGV_RIGHT = 0
P_IMGV_UP_RIGHT = TILE_SIZE * 1
P_IMGV_DOWN_RIGHT = TILE_SIZE * 5
P_IMGV_STOP_UP = TILE_SIZE * 7
P_IMGV_STOP_DOWN = TILE_SIZE * 8
P_IMGV_STOP_JUMP_RIGHT = TILE_SIZE * 2
P_IMGV_JUMP_RIGHT = TILE_SIZE * 3
P_IMGV_JUMP_UP_RIGHT = TILE_SIZE * 4
P_IMGV_JUMP_DOWN_RIGHT = TILE_SIZE * 6
P_IMGV_JUMP_UP = TILE_SIZE * 9
P_IMGV_JUMP_DOWN = TILE_SIZE * 10


class Direction(Enum):
    RIGHT = 0
    LEFT = 1
    DOWN = 2
    UP = 3
